###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "firstName":  "michael",
  "lastName":  "de Kaste",
  "email" : "m.dekaste@hotmail.com"
}

###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "firstName":  "",
  "lastName":  "de Oaste",
  "email" : "m.dekastehotmail.com"
}

###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "firstName":  "Jantje",
  "lastName":  "van Achterwijk",
  "email" : "jvana@topicus.nl"
}

###
GET http://127.0.0.1:8080/customer
Content-Type: application/json

###
GET http://127.0.0.1:8080/customer/e172286f-54e2-4dbf-9307-81c5ac00255e
Content-Type: application/json

